<img src="http://iran-datascience.ir/SoheilTP/logo.jpg" />

<div class="alert alert-block alert-success">
    <h1 align="center">Machine Learning in Python</h1>
    <h3 align="center">Day 001: Numpy</h3>
    <h4 align="center"><a href="http://www.iran-machinelearning.ir">Soheil Tehranipour</a></h5>
</div>

> You can follow me in :
* [Linkedin](https://www.linkedin.com/in/soheiltehrani/). 
* [Instagram](https://www.instagram.com/soheiltehranipour/).
* [Github](https://github.com/soheiltehranipour).
* Website : www.iran-machinelearning.ir


<img src = "https://www.edureka.co/blog/wp-content/uploads/2017/07/Python-Numpy_05.gif">

# Numpy
NumPy is a Python package which stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++ etc. 

It is also useful in linear algebra, random number capability etc. NumPy array can also be used as an efficient multi-dimensional container for generic data. Now, let me tell you what exactly is a python numpy array.

<img src = "http://iran-datascience.ir/SoheilTP/numpy.png">

## NumPy Array
Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize numpy arrays from nested Python lists and access it elements. In order to perform these numpy operations, the next question which will come in your mind is:

In [2]:
import numpy as np

In [3]:
np.__version__

'1.15.2'

In [4]:
print(np.__version__)

1.15.2


<img src = "http://iran-datascience.ir/SoheilTP/array.png">

## Creating arrays in numpy

In [5]:
x = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(np.where(x > 5, x, 0))

[[0 0 0]
 [0 0 6]
 [7 8 9]]


In [ ]:
print(type(x))

<img src="https://d1jnx9ba8s6j9r.cloudfront.net/blog/wp-content/uploads/2017/06/MultiDimensional-Array.png" width="75%"/>



## Shape and Reshape in numpy

In [8]:
print(x.shape)

(3, 3)


In [9]:
print(x.shape[0])

3


In [10]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array (or matrix)

In [11]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(np.reshape(A, (3, 2)))

[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(np.reshape(A, (1, -1)))  # -1 means the number of columns will be determined automatically

[[1 2 3 4 5 6]]


<img src="https://d1jnx9ba8s6j9r.cloudfront.net/blog/wp-content/uploads/2017/06/Reshape.jpg" width="75%"/>

In [14]:
print(np.reshape(A, (-1, 1)))   # -1 means the number of rows will be determined automatically

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Arrays in numpy

In [18]:
print(x.ndim)

2


In [20]:
print(A.dtype)

int64


In [21]:
A = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

In [22]:
print(A.dtype)

float32


In [25]:
print(A.size)  # number of elements

6


In [23]:
print(A.itemsize)  # size of each element (in bytes)

4


## arange in numpy

In [26]:
x1 = np.arange(1, 20, step=3)
print(x1)

[ 1  4  7 10 13 16 19]


In [27]:
np.arange

<function numpy.core.multiarray.arange>

## linspace in numpy

In [29]:
x2 = np.linspace(1, 2, num=5)
print(x2)

[1.   1.25 1.5  1.75 2.  ]


In [30]:
x3 = np.linspace(1, 2, num=11)
print(x3)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]


### Creating specific arrays
- `np.zeros`
- `np.ones`
- `np.full`
- `np.eye`

In [31]:
print(np.zeros(shape=(2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
print(np.zeros(shape=(2, 3), dtype=np.int32))

[[0 0 0]
 [0 0 0]]


In [34]:
print(np.ones(shape=(3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [35]:
print(5. * np.ones(shape=(3, 2)))

[[5. 5.]
 [5. 5.]
 [5. 5.]]


In [36]:
print(np.full((3, 2), 5))

[[5 5]
 [5 5]
 [5 5]]


In [37]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
print(np.fliplr(np.eye(4)))

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [39]:
print(np.random.rand(3, 2))

[[0.31183735 0.66873826]
 [0.74056186 0.86405969]
 [0.00508425 0.2006781 ]]


## Operations on numpy arrays

In [40]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x)
print()
print(y)

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]


In [41]:
# Elementwise sum; both produce the array
print(x + y)
print()
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [42]:
# Elementwise difference; both produce the array
print(x - y)
print()
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [43]:
# Elementwise product; both produce the array
print(x * y)
print()
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [44]:
# Elementwise division; both produce the array
print(x / y)
print()
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [45]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
